### PR TITLE
FitSNAP as a Library

### PR DESCRIPTION
**Pull request by jan-janssen**
Here is the code we just discussed. Unfortunately I was not able to push to my previous pull request https://github.com/FitSNAP/FitSNAP/pull/65 as I was switching between internal Gitlab and Github. But the changes follow the same concept.

### CODE REVIEW

**Comment by charlessievers** [comment]
Thanks Jan. Do you have an ipynb or just *.py example I could run and use for testing to make sure any changes I make won't break what you guys want out of FitSNAP?

**Comment by jan-janssen** [comment]
Sure, I uploaded the notebooks to https://github.com/jan-janssen/fitsnap-libray-notebooks

* [test-singleton.ipynb](https://github.com/jan-janssen/fitsnap-libray-notebooks/blob/main/test-singleton.ipynb) - tests that the singleton is working, so I always get the same instance of ParallelTools. 
* [test-lammps.ipynb](https://github.com/jan-janssen/fitsnap-libray-notebooks/blob/main/test-lammps.ipynb) - the second example is the notebook I showed in the meeting. We would like to calculate the bispectrum components directly after the DFT calculation, so if this functionality would be available in a Python library that would be great.

**Review by rohskopf — COMMENTED** [review]
We'd like to add these changes but need to resolve some errors first. 

When running on this branch, I get the following error:

```
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.10/3.10.4/Frameworks/Python.framework/Versions/3.10/lib/python3.10/pkgutil.py", line 417, in get_importer
    importer = sys.path_importer_cache[path_item]
KeyError: PosixPath('/Users/adrohsk/FitSNAP/fitsnap3/units')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.10/3.10.4/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/Cellar/python@3.10/3.10.4/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/adrohsk/FitSNAP/fitsnap3/__main__.py", line 31, in <module>
    from fitsnap3.fitsnap import FitSnap
  File "/Users/adrohsk/FitSNAP/fitsnap3/fitsnap.py", line 34, in <module>
    from fitsnap3.scrapers.scraper_factory import scraper
  File "/Users/adrohsk/FitSNAP/fitsnap3/scrapers/scraper_factory.py", line 1, in <module>
    from fitsnap3.scrapers.scrape import Scraper
  File "/Users/adrohsk/FitSNAP/fitsnap3/scrapers/scrape.py", line 38, in <module>
    from fitsnap3.units.units import convert
  File "/Users/adrohsk/FitSNAP/fitsnap3/units/units.py", line 1, in <module>
    from fitsnap3.units.conversion_finder import create_conversion
  File "/Users/adrohsk/FitSNAP/fitsnap3/units/conversion_finder.py", line 16, in <module>
    for (_, unit_type, c) in iter_modules([unit_dir]):
  File "/usr/local/Cellar/python@3.10/3.10.4/Frameworks/Python.framework/Versions/3.10/lib/python3.10/pkgutil.py", line 129, in iter_modules
    for i in importers:
  File "/usr/local/Cellar/python@3.10/3.10.4/Frameworks/Python.framework/Versions/3.10/lib/python3.10/pkgutil.py", line 421, in get_importer
    importer = path_hook(path_item)
  File "<frozen importlib._bootstrap_external>", line 1632, in path_hook_for_FileFinder
  File "<frozen importlib._bootstrap_external>", line 1504, in __init__
  File "<frozen importlib._bootstrap_external>", line 182, in _path_isabs
AttributeError: 'PosixPath' object has no attribute 'startswith'
```

To reproduce this try doing `python -m fitsnap3 Ta-example.in` in `examples/Ta_Linear_JCP2014`

**Comment by rohskopf** [comment]
I get the same error when importing FitSNAP in a python script:

```
from fitsnap3.io.input import Config
config = Config(arguments_lst = ["Ta-example.in","--overwrite"])
from fitsnap3.fitsnap import FitSnap
```

But this seemed to work in [Jan's notebook](https://github.com/jan-janssen/fitsnap-libray-notebooks/blob/main/test-lammps.ipynb)

**Comment by rohskopf** [comment]
These library imports were not working for me on a Python 3.10.4 virtual environment, because of the above errors.

It does work on a python 3.8 conda environment. 

Now we just gotta port these new library imports to the updated FitSNAP. I'd be happy to do that.

**Review by mitwood — APPROVED** [review]

**Comment by rohskopf** [comment]
The previous errors happened with homebrew python 3.10.4. After trying again with a conda python 3.8 environment, it works just fine.
